--Buscas dos processos

-- Por NrProcesso

SELECT 
    PROC.NR_PROCESSO,
    PROC.DS_PROCESSO,
    CLI.DS_RAZAO_SOCIAL
     
FROM T_AM_NTW_PROCESSO PROC
INNER JOIN T_AM_NTW_CLIENTE CLI ON (PROC.CD_CLIENTE = CLI.CD_CLIENTE)

  WHERE PROC.NR_PROCESSO = 2
  AND PROC.DT_FECHAMENTO IS NULL;

-- Por razão social

SELECT 
    PROC.NR_PROCESSO,
    PROC.DS_PROCESSO,
    CLI.DS_RAZAO_SOCIAL
     
FROM T_AM_NTW_PROCESSO PROC
INNER JOIN T_AM_NTW_CLIENTE CLI ON (PROC.CD_CLIENTE = CLI.CD_CLIENTE)

  WHERE CLI.DS_RAZAO_SOCIAL = 'ALEGRIA CELESTIAL'
  AND PROC.DT_FECHAMENTO IS NULL;

-- Período

SELECT 
    PROC.NR_PROCESSO,
    PROC.DS_PROCESSO,
    CLI.DS_RAZAO_SOCIAL
     
FROM T_AM_NTW_PROCESSO PROC
INNER JOIN T_AM_NTW_CLIENTE CLI ON (PROC.CD_CLIENTE = CLI.CD_CLIENTE)

  WHERE DT_ABERTURA >= TO_DATE('24/05/2010', 'DD/MM/YYYY') AND DT_ABERTURA <= TO_DATE('25/05/2014', 'DD/MM/YYYY')
  AND PROC.DT_FECHAMENTO IS NULL;
  
  -- Busca situação processo
  
SELECT 
  NR_SITUACAO

FROM T_AM_NTW_PROCESSO
  WHERE NR_PROCESSO = 1;
  